export enum Strings {
  CONTAINER_NAME = "cesiumContainer",
  MAPBOX_ACCESS_TOKEN = "pk.eyJ1IjoiYW5hbHl0aWNhbGdyYXBoaWNzIiwiYSI6ImNpd204Zm4wejAwNzYyeW5uNjYyZmFwdWEifQ.7i-VIZZWX8pd1bTfxIVj9g",
  MAPBOX_STYLE_ID = "streets-v11",
  MAPBOX_USERNAME = "mapbox",
  CESIUM_ION_DEFAULT_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiZjgzZWU4ZS0zNDMxLTRlM2EtODg5Yi01ODcxY2EzZTc4YjIiLCJpZCI6MjE0NzUsInNjb3BlcyI6WyJhc3IiLCJnYyJdLCJpYXQiOjE1Nzk2NjQ2NDR9.ZM8dJsvr-vdTpTK1PvZVznEsHVRIC7nyvFyw3yYngtE"
}
